'use strict';
const { prisma } = require('../../config/database');
const BUSINESS_TIMEZONE = 'Asia/Kolkata'; const BLOCKING_AVAILABILITY = new Set(['unavailable', 'maintenance', 'blocked']); const BLOCKING_BOOKING = new Set(['PENDING', 'PAYMENT_PENDING', 'CONFIRMED', 'ACTIVE']);
const formatter = new Intl.DateTimeFormat('en-CA', { timeZone: BUSINESS_TIMEZONE, year: 'numeric', month: '2-digit', day: '2-digit' });
function businessDate(value) { const parts = formatter.formatToParts(new Date(value)); const get = (type) => parts.find((part) => part.type === type).value; return `${get('year')}-${get('month')}-${get('day')}`; }
function requestDays(pickup, dropoff) { const days = new Set(); const cursor = new Date(pickup); const last = new Date(new Date(dropoff).getTime() - 1); while (cursor <= last) { days.add(businessDate(cursor)); cursor.setTime(cursor.getTime() + 24 * 60 * 60 * 1000); } return days; }
function overlaps(startA, endA, startB, endB) { return new Date(startA) < new Date(endB) && new Date(endA) > new Date(startB); }
function isRentable(car) { return Boolean(car && !car.isDeleted && car.status === 'available'); }
function conflictFromConfiguration(records, pickup, dropoff) { const days = requestDays(pickup, dropoff); for (const record of records) { if (!BLOCKING_AVAILABILITY.has(record.status)) continue; if (!record.startTime || !record.endTime) { if (days.has(businessDate(record.date))) return record.status === 'maintenance' ? 'MAINTENANCE' : record.status === 'blocked' ? 'BLOCKED' : 'UNAVAILABLE'; } else if (overlaps(record.startTime, record.endTime, pickup, dropoff)) return record.status === 'maintenance' ? 'MAINTENANCE' : record.status === 'blocked' ? 'BLOCKED' : 'UNAVAILABLE'; } return null; }
function conflictFromBookings(bookings, pickup, dropoff) { const now = new Date(); return bookings.some((booking) => { const temporary = booking.status === 'PENDING' || booking.status === 'PAYMENT_PENDING'; const blocks = temporary ? booking.holdExpiresAt && new Date(booking.holdExpiresAt) > now : BLOCKING_BOOKING.has(booking.status); return blocks && overlaps(booking.startAt, booking.endAt, pickup, dropoff); }) ? 'BOOKING_CONFLICT' : null; }
async function conflictSources(carIds, db=prisma) { const ids = carIds.filter(Boolean); if (!ids.length) return { configurations: [], bookings: [] }; const [configurations, bookings] = await Promise.all([db.carAvailability.findMany({ where: { carId: { in: ids } } }), db.booking.findMany({ where: { carId: { in: ids } } })]); return { configurations, bookings }; }
function availabilityFor(car, pickup, dropoff, sources) { if (!isRentable(car)) return { available: false, reasonCode: 'CAR_NOT_RENTABLE' }; const configured = conflictFromConfiguration(sources.configurations.filter((record) => record.carId === car.id), pickup, dropoff); if (configured) return { available: false, reasonCode: configured }; const booking = conflictFromBookings(sources.bookings.filter((record) => record.carId === car.id), pickup, dropoff); return booking ? { available: false, reasonCode: booking } : { available: true }; }
async function checkCarAvailability(carId, pickup, dropoff, db=prisma) { const car = await db.car.findUnique({ where: { id: carId }, include: { images: true, features: true } }); if (!car || car.isDeleted) return { available: false, reasonCode: 'CAR_NOT_FOUND', car: null }; const sources = await conflictSources([carId], db); return { ...availabilityFor(car, pickup, dropoff, sources), car }; }
async function searchAvailableCars(filters) { const where = { isDeleted: false, status: 'available', ...(filters.branchId ? { branchId: filters.branchId } : {}), ...(filters.vendorId ? { vendorId: filters.vendorId } : {}), ...(filters.brand ? { brand: { contains: filters.brand } } : {}), ...(filters.fuelType ? { fuelType: filters.fuelType } : {}), ...(filters.transmission ? { transmission: filters.transmission } : {}), ...(filters.seats ? { seatingCapacity: { gte: filters.seats } } : {}) }; if (filters.locationId) { const branches = await prisma.branch.findMany({ where: { locationId: filters.locationId } }); where.branchId = { in: branches.map((branch) => branch.id) }; } const candidates = await prisma.car.findMany({ where, include: { images: true, features: true, pricings: true, branch: true } }); const sources = await conflictSources(candidates.map((car) => car.id)); return candidates.filter((car) => availabilityFor(car, filters.pickupDateTime, filters.returnDateTime, sources).available); }
module.exports = { BUSINESS_TIMEZONE, overlaps, isRentable, checkCarAvailability, searchAvailableCars, availabilityFor };
