'use strict';
const jwt = require('jsonwebtoken'); const crypto = require('crypto'); const { prisma } = require('../../config/database'); const { env } = require('../../config/env'); const AppError = require('../../errors/AppError'); const httpStatus = require('../../constants/httpStatus'); const errorCodes = require('../../errors/errorCodes'); const { checkCarAvailability } = require('../availability/service');
function selectPricingRecord(records, pickup) { return records.filter((record) => record.status === 'active' && (!record.effectiveFrom || new Date(record.effectiveFrom) <= new Date(pickup)) && (!record.effectiveTo || new Date(record.effectiveTo) >= new Date(pickup))).sort((a, b) => (new Date(b.effectiveFrom || 0) - new Date(a.effectiveFrom || 0)) || (new Date(b.createdAt || 0) - new Date(a.createdAt || 0)) || String(b.id).localeCompare(String(a.id)))[0] || null; }
function money(value) { return Math.round((value + Number.EPSILON) * 100) / 100; }
function calculateRentalPrice(pricing, pickup, dropoff) { let remaining = Math.ceil((new Date(dropoff) - new Date(pickup)) / 3600000); const units = []; let subtotal = 0; const add = (name, hours, rate) => { const count = Math.floor(remaining / hours); if (count && rate !== null && rate !== undefined) { subtotal += count * Number(rate); remaining -= count * hours; units.push({ unit: name, count, rate: Number(rate), amount: money(count * Number(rate)) }); } }; add('month', 720, pricing.monthlyPrice); add('week', 168, pricing.weeklyPrice); add('day', 24, pricing.dailyPrice); if (remaining) { if (pricing.hourlyPrice !== null && pricing.hourlyPrice !== undefined) { subtotal += remaining * Number(pricing.hourlyPrice); units.push({ unit: 'hour', count: remaining, rate: Number(pricing.hourlyPrice), amount: money(remaining * Number(pricing.hourlyPrice)) }); } else { subtotal += Number(pricing.dailyPrice); units.push({ unit: 'day', count: 1, rate: Number(pricing.dailyPrice), amount: Number(pricing.dailyPrice) }); } } const billableHours = Math.ceil((new Date(dropoff) - new Date(pickup)) / 3600000); return { totalMinutes: Math.ceil((new Date(dropoff) - new Date(pickup)) / 60000), billableHours, breakdown: units, rentalSubtotal: money(subtotal) }; }
function signQuote(payload) { return jwt.sign(payload, env.QUOTE_SIGNING_SECRET, { expiresIn: `${env.QUOTE_TTL_MINUTES}m`, audience: 'rentcar-quote', issuer: 'rentcar-api' }); }
function verifyQuote(token) { return jwt.verify(token, env.QUOTE_SIGNING_SECRET, { audience: 'rentcar-quote', issuer: 'rentcar-api' }); }
async function createTrustedQuote({ carId, pickupDateTime, returnDateTime }) { const availability = await checkCarAvailability(carId, pickupDateTime, returnDateTime); if (!availability.car) throw new AppError('Car not found.', httpStatus.NOT_FOUND, errorCodes.RESOURCE_NOT_FOUND); if (!availability.available) throw new AppError('Car is not available for the requested interval.', httpStatus.CONFLICT, errorCodes.CONFLICT, { reasonCode: availability.reasonCode }); const records = await prisma.carPricing.findMany({ where: { carId } }); const pricing = selectPricingRecord(records, pickupDateTime); if (!pricing) throw new AppError('No active pricing record is available for this car.', httpStatus.NOT_FOUND, errorCodes.RESOURCE_NOT_FOUND); const duration = calculateRentalPrice(pricing, pickupDateTime, returnDateTime); const securityDeposit = money(Number(pricing.securityDeposit || 0)); const payableAmount = money(duration.rentalSubtotal + securityDeposit); const expiresAt = new Date(Date.now() + env.QUOTE_TTL_MINUTES * 60000).toISOString(); const quoteId = crypto.randomUUID(); const payload = { quoteId, carId, pickupDateTime, returnDateTime, pricingId: pricing.id, currencyCode: pricing.currencyCode, rentalSubtotal: duration.rentalSubtotal, securityDeposit, payableAmount, expiresAt }; return { quoteId, carId, pickupDateTime, returnDateTime, currencyCode: pricing.currencyCode, duration, pricing: { pricingId: pricing.id, rentalSubtotal: duration.rentalSubtotal, securityDeposit, payableAmount }, expiresAt, availability: { available: true, held: false }, quoteToken: signQuote(payload) }; }
module.exports = { selectPricingRecord, calculateRentalPrice, createTrustedQuote, verifyQuote };
