'use strict';
jest.mock('../src/modules/payments/providers/razorpay', () => ({ createRefund: jest.fn(), createOrder: jest.fn(), verifyCheckoutSignature: jest.fn(), verifyWebhookSignature: jest.fn(), parseWebhookEvent: jest.fn() }));
const request = require('supertest'); const { createApp } = require('../src/app'); const { prisma, resetStore, seedUser } = require('./helpers/auth'); const { signAccessToken } = require('../src/utils/jwt'); const { checkCarAvailability } = require('../src/modules/availability/service'); const razorpay = require('../src/modules/payments/providers/razorpay');
async function fixture({ paid = false, status = paid ? 'CONFIRMED' : 'PAYMENT_PENDING', startAt = new Date(Date.now() + 86400000) } = {}) { const user = await seedUser({ email: `cancel-${Math.random()}@test` }); const car = await prisma.car.create({ data: { vendorId: 'v', branchId: 'b', registrationNumber: `C-${Math.random()}`, brand: 'T', model: 'C', manufacturingYear: 2025, status: 'available' } }); const booking = await prisma.booking.create({ data: { bookingNumber: `C-${Math.random()}`, userId: user.id, vendorId: 'v', carId: car.id, startAt, endAt: new Date(startAt.getTime() + 3600000), subtotal: 100, totalAmount: 100, currencyCode: 'INR', status, paymentStatus: paid ? 'succeeded' : 'pending', holdExpiresAt: new Date(Date.now() + 3600000) } }); if (paid) await prisma.payment.create({ data: { bookingId: booking.id, userId: user.id, amount: 100, currencyCode: 'INR', provider: 'razorpay', providerPaymentId: `pay_${booking.id}`, status: 'succeeded' } }); return { user, booking }; }
describe('booking cancellation', () => { let app; beforeAll(() => { app = createApp(); }); beforeEach(() => { resetStore(); razorpay.createRefund.mockResolvedValue({ providerRefundId: 'rfnd_cancel', status: 'pending' }); }); const cancel = (token, id, key = 'cancel-key', body = {}) => request(app).post(`/api/v1/bookings/${id}/cancel`).set('Authorization', `Bearer ${token}`).set('Idempotency-Key', key).send(body);
it('enforces auth, ownership, and strict bodies', async () => { const f = await fixture(); expect((await request(app).post(`/api/v1/bookings/${f.booking.id}/cancel`).set('Idempotency-Key', 'x').send({})).status).toBe(401); const other = await seedUser({ email: `other-${Math.random()}@test` }); expect((await cancel(signAccessToken({ sub: other.id }), f.booking.id)).status).toBe(404); expect((await cancel(signAccessToken({ sub: f.user.id }), f.booking.id, 'x', { amount: 1 })).status).toBe(422); });
it('cancels unpaid once with audit fields and history', async () => { const f = await fixture(); const token = signAccessToken({ sub: f.user.id }); expect((await cancel(token, f.booking.id, 'one', { reason: 'Changed plans' })).status).toBe(200); expect((await cancel(token, f.booking.id, 'two')).status).toBe(200); const saved = await prisma.booking.findUnique({ where: { id: f.booking.id } }); expect(saved).toMatchObject({ status: 'CANCELLED', cancellationReason: 'Changed plans' }); expect(saved.cancelledAt).toBeTruthy(); expect(await prisma.bookingStatusHistory.count({ where: { bookingId: f.booking.id } })).toBe(1); });
it('creates one paid refund and rejects non-cancellable lifecycle states', async () => { const f = await fixture({ paid: true }); const token = signAccessToken({ sub: f.user.id }); await cancel(token, f.booking.id, 'paid-one'); await cancel(token, f.booking.id, 'paid-two'); expect(await prisma.refund.count({ where: { bookingId: f.booking.id } })).toBe(1); expect((await prisma.refund.findFirst({ where: { bookingId: f.booking.id } })).amount).toBe(100); const blocked = await fixture({ status: 'ACTIVE', startAt: new Date(Date.now() + 86400000) }); expect((await cancel(signAccessToken({ sub: blocked.user.id }), blocked.booking.id)).status).toBe(409); });
it('releases an active temporary hold through the actual availability service', async () => { const f = await fixture(); const token = signAccessToken({ sub: f.user.id }); expect((await checkCarAvailability(f.booking.carId, f.booking.startAt, f.booking.endAt)).available).toBe(false); await cancel(token, f.booking.id); expect((await checkCarAvailability(f.booking.carId, f.booking.startAt, f.booking.endAt)).available).toBe(true); });
it('rejects exact/after-start paid cancellations and terminal states without mutations', async () => { const now = new Date('2031-01-01T00:00:00.000Z'); jest.useFakeTimers().setSystemTime(now); try { const exact = await fixture({ paid: true, startAt: now }); const late = await fixture({ paid: true, startAt: new Date(now.getTime() - 1) }); const completed = await fixture({ status: 'COMPLETED' }); for (const f of [exact, late, completed]) { expect((await cancel(signAccessToken({ sub: f.user.id }), f.booking.id)).status).toBe(409); expect(await prisma.refund.count({ where: { bookingId: f.booking.id } })).toBe(0); } } finally { jest.useRealTimers(); } }); });
it('reuses an existing durable refund and keeps cancellation responses safe', async () => { const app = createApp(); const f = await fixture({ paid: true }); const payment = await prisma.payment.findFirst({ where: { bookingId: f.booking.id } }); const existing = await prisma.refund.create({ data: { bookingId: f.booking.id, paymentId: payment.id, amount: 100, currencyCode: 'INR', provider: 'razorpay', idempotencyKey: 'persisted_refund_key', status: 'pending' } }); const response = await request(app).post(`/api/v1/bookings/${f.booking.id}/cancel`).set('Authorization', `Bearer ${signAccessToken({ sub: f.user.id })}`).set('Idempotency-Key', 'different_key').send({}); expect(response.status).toBe(200); expect(await prisma.refund.count({ where: { bookingId: f.booking.id } })).toBe(1); expect((await prisma.refund.findFirst({ where: { bookingId: f.booking.id } })).idempotencyKey).toBe(existing.idempotencyKey); expect(JSON.stringify(response.body)).not.toContain('idempotencyKey'); });
