'use strict';
const request = require('supertest');
const { createApp } = require('../src/app');
const { prisma, resetStore, seedRole, seedUser } = require('./helpers/auth');
const { signAccessToken } = require('../src/utils/jwt');
const { pickupBooking } = require('../src/modules/bookings/service');

describe('protected booking pickup', () => {
  let app; let member; let customer; let vendor; let booking; let car;
  const token = (user) => signAccessToken({ sub: user.id, type: 'access' });
  const pickup = (user, body = { startOdometer: 100, fuelLevelPercent: 75 }) => request(app).post(`/api/v1/bookings/${booking.id}/pickup`).set('Authorization', `Bearer ${token(user)}`).send(body);
  beforeAll(() => { app = createApp(); });
  beforeEach(async () => { resetStore(); await seedRole('OPERATOR', { permissions: ['bookings.operate'] }); member = await seedUser({ email: `op-${Math.random()}@test`, roles: ['OPERATOR'] }); customer = await seedUser({ email: `customer-${Math.random()}@test` }); vendor = await prisma.vendor.create({ data: { vendorCode: `V-${Math.random()}`, companyName: 'Vendor' } }); await prisma.vendorMember.create({ data: { vendorId: vendor.id, userId: member.id, isOwner: true } }); car = await prisma.car.create({ data: { vendorId: vendor.id, branchId: 'branch', registrationNumber: `P-${Math.random()}`, brand: 'T', model: 'X', manufacturingYear: 2025, status: 'available', odometer: 100 } }); booking = await prisma.booking.create({ data: { bookingNumber: `P-${Math.random()}`, userId: customer.id, vendorId: vendor.id, carId: car.id, startAt: new Date(), endAt: new Date(Date.now() + 3600000), subtotal: 1, totalAmount: 1, currencyCode: 'INR', status: 'CONFIRMED', paymentStatus: 'succeeded' } }); });
  it('requires bookings.operate and vendor membership, then records an atomic pickup', async () => { expect((await pickup(customer)).status).toBe(403); const outsider = await seedUser({ email: `out-${Math.random()}@test`, roles: ['OPERATOR'] }); expect((await pickup(outsider)).status).toBe(404); const response = await pickup(member, { startOdometer: 120, fuelLevelPercent: 75, notes: '  ready  ' }); expect(response.status).toBe(200); expect(response.body.data).toMatchObject({ bookingId: booking.id, status: 'ACTIVE', carStatus: 'busy', pickup: { odometer: 120, fuelLevelPercent: 75 } }); const trip = await prisma.tripHistory.findUnique({ where: { bookingId: booking.id } }); expect(trip).toMatchObject({ startOdometer: 120, startFuel: 75, startedBy: member.id, pickupNotes: 'ready', tripStatus: 'active' }); expect(await prisma.bookingStatusHistory.count({ where: { bookingId: booking.id, toStatus: 'ACTIVE' } })).toBe(1); expect(await prisma.auditLog.count({ where: { action: 'booking.pickup.completed' } })).toBe(1); expect((await prisma.car.findUnique({ where: { id: car.id } })).odometer).toBe(120); });
  it('is durable-idempotent and rejects conflicting retries', async () => { expect((await pickup(member)).status).toBe(200); expect((await pickup(member)).body.data.replayed).toBe(true); expect((await pickup(member, { startOdometer: 101, fuelLevelPercent: 75 })).status).toBe(409); expect(await prisma.bookingStatusHistory.count({ where: { bookingId: booking.id } })).toBe(1); expect(await prisma.auditLog.count({ where: { action: 'booking.pickup.completed' } })).toBe(1); });
  it('validates inputs and payment/car preconditions without mutation', async () => { expect((await pickup(member, { startOdometer: 99, fuelLevelPercent: 75 })).status).toBe(422); expect((await pickup(member, { startOdometer: 100, fuelLevelPercent: 101 })).status).toBe(422); expect((await pickup(member, { startOdometer: 100.5, fuelLevelPercent: 75 })).status).toBe(422); await prisma.booking.update({ where: { id: booking.id }, data: { paymentStatus: 'pending' } }); expect((await pickup(member)).status).toBe(409); await prisma.booking.update({ where: { id: booking.id }, data: { paymentStatus: 'succeeded' } }); await prisma.car.update({ where: { id: car.id }, data: { status: 'maintenance' } }); expect((await pickup(member)).status).toBe(409); });
  it('rolls all pickup changes back when its internal service seam throws', async () => { await expect(pickupBooking({ operatorId: member.id, bookingId: booking.id, startOdometer: 100, fuelLevelPercent: 0, testHooks: { afterPickupMutation: async () => { throw new Error('rollback'); } } })).rejects.toThrow('rollback'); expect((await prisma.booking.findUnique({ where: { id: booking.id } })).status).toBe('CONFIRMED'); expect((await prisma.car.findUnique({ where: { id: car.id } })).status).toBe('available'); expect(await prisma.tripHistory.count()).toBe(0); expect(await prisma.bookingStatusHistory.count()).toBe(0); expect(await prisma.auditLog.count({ where: { action: 'booking.pickup.completed' } })).toBe(0); expect((await pickup(member, { startOdometer: 100, fuelLevelPercent: 0 })).status).toBe(200); });
});
