'use strict';

const fs = require('fs');
const path = require('path');
const request = require('supertest');
const { createApp } = require('../src/app');
const { prisma, resetStore, seedUser } = require('./helpers/auth');
const { signAccessToken } = require('../src/utils/jwt');
const { userKycDocumentDir } = require('../src/middlewares/upload');

const pdf = Buffer.from('%PDF-1.4 KYC');
describe('customer KYC documents', () => {
  let app; let owner; let other; let token; let otherToken;
  beforeAll(() => { app = createApp(); });
  beforeEach(async () => { resetStore(); fs.mkdirSync(userKycDocumentDir, { recursive: true }); owner = await seedUser({ email: `kyc-owner-${Math.random()}@test` }); other = await seedUser({ email: `kyc-other-${Math.random()}@test` }); token = signAccessToken({ sub: owner.id, type: 'access' }); otherToken = signAccessToken({ sub: other.id, type: 'access' }); });
  afterEach(() => { if (fs.existsSync(userKycDocumentDir)) fs.readdirSync(userKycDocumentDir).forEach((file) => fs.unlinkSync(path.join(userKycDocumentDir, file))); });
  const upload = (auth = token, fields = {}) => request(app).post('/api/v1/kyc/documents').set('Authorization', `Bearer ${auth}`).field('documentType', fields.documentType || 'driving_license').field('expiresAt', fields.expiresAt || '2035-01-01').attach('file', fields.bytes || pdf, { filename: fields.filename || 'licence.pdf', contentType: fields.mime || 'application/pdf' });

  it('stores a private random file and returns a safe DTO', async () => { const response = await upload(); expect(response.status).toBe(201); expect(response.body.data).not.toHaveProperty('storageKey'); expect(response.body.data).not.toHaveProperty('verifiedBy'); expect(await prisma.userDocument.count({ where: { userId: owner.id } })).toBe(1); const stored = await prisma.userDocument.findFirst({ where: { userId: owner.id } }); expect(stored.storageKey).not.toContain('/'); expect(fs.existsSync(path.join(userKycDocumentDir, stored.storageKey))).toBe(true); expect((await request(app).get(`/uploads/private/users/${stored.storageKey}`)).status).not.toBe(200); const event = await prisma.auditLog.findFirst({ where: { action: 'kyc.customer.document_uploaded' } }); expect(event.metadata).not.toContain('storageKey'); expect(event.metadata).not.toContain('uploads'); });
  it('rejects invalid input and missing files without leaving validation artifacts', async () => { expect((await request(app).post('/api/v1/kyc/documents').set('Authorization', `Bearer ${token}`).field('documentType', 'bad').attach('file', pdf, { filename: 'x.pdf', contentType: 'application/pdf' })).status).toBe(422); expect(fs.readdirSync(userKycDocumentDir)).toEqual([]); expect((await request(app).post('/api/v1/kyc/documents').set('Authorization', `Bearer ${token}`).field('documentType', 'pan')).status).toBe(422); expect((await upload(token, { mime: 'text/plain', filename: 'x.txt' })).status).toBe(400); expect((await request(app).post('/api/v1/kyc/documents').set('Authorization', `Bearer ${token}`).field('documentType', 'driving_license').attach('file', pdf, { filename: 'x.pdf', contentType: 'application/pdf' })).status).toBe(422); expect(fs.readdirSync(userKycDocumentDir)).toEqual([]); });
  it('enforces owner-only list, detail, download, and delete', async () => { await upload(); const doc = await prisma.userDocument.findFirst({ where: { userId: owner.id } }); expect((await request(app).get('/api/v1/kyc/documents').set('Authorization', `Bearer ${token}`)).body.data).toHaveLength(1); expect((await request(app).get(`/api/v1/kyc/documents/${doc.id}`).set('Authorization', `Bearer ${otherToken}`)).status).toBe(404); expect((await request(app).get(`/api/v1/kyc/documents/${doc.id}/download`).set('Authorization', `Bearer ${otherToken}`)).status).toBe(404); expect((await request(app).delete(`/api/v1/kyc/documents/${doc.id}`).set('Authorization', `Bearer ${otherToken}`)).status).toBe(404); expect((await request(app).get(`/api/v1/kyc/documents/${doc.id}/download`).set('Authorization', `Bearer ${token}`)).status).toBe(200); });
  it('deletes only pending evidence and cleans its file', async () => { await upload(); const doc = await prisma.userDocument.findFirst({ where: { userId: owner.id } }); const file = path.join(userKycDocumentDir, doc.storageKey); expect((await request(app).delete(`/api/v1/kyc/documents/${doc.id}`).set('Authorization', `Bearer ${token}`)).status).toBe(200); expect(fs.existsSync(file)).toBe(false); expect(await prisma.userDocument.findUnique({ where: { id: doc.id } })).toBeNull(); const reviewed = await prisma.userDocument.create({ data: { userId: owner.id, documentType: 'pan', storageKey: 'reviewed.pdf', status: 'verified' } }); expect((await request(app).delete(`/api/v1/kyc/documents/${reviewed.id}`).set('Authorization', `Bearer ${token}`)).status).toBe(409); });
  it('cleans the uploaded file when document persistence fails', async () => { const original = prisma.userDocument.create; prisma.userDocument.create = async () => { throw new Error('database failure'); }; try { expect((await upload()).status).toBe(500); expect(fs.readdirSync(userKycDocumentDir)).toEqual([]); } finally { prisma.userDocument.create = original; } });
  it('retains rejected evidence when a replacement is uploaded', async () => { const rejected = await prisma.userDocument.create({ data: { userId: owner.id, documentType: 'driving_license', storageKey: 'old.pdf', status: 'rejected' } }); await upload(); const documents = await prisma.userDocument.findMany({ where: { userId: owner.id } }); expect(documents).toHaveLength(2); expect(documents.find((document) => document.id === rejected.id).status).toBe('rejected'); expect(documents.find((document) => document.id !== rejected.id).status).toBe('pending'); });
});
