'use strict';
jest.mock('../src/modules/payments/providers/razorpay', () => ({ createOrder: jest.fn(), verifyCheckoutSignature: jest.fn(), verifyWebhookSignature: jest.fn(), parseWebhookEvent: jest.fn() }));
const request = require('supertest'); const { createApp } = require('../src/app'); const { prisma, resetStore, seedUser } = require('./helpers/auth'); const razorpay = require('../src/modules/payments/providers/razorpay');
async function fixture() { const user = await seedUser({ email: 'webhook@example.test' }); const car = await prisma.car.create({ data: { vendorId: 'v', branchId: 'b', registrationNumber: `WH-${Math.random()}`, brand: 'T', model: 'W', manufacturingYear: 2025, status: 'available' } }); const booking = await prisma.booking.create({ data: { bookingNumber: `BK-${Math.random()}`, userId: user.id, vendorId: 'v', carId: car.id, startAt: new Date('2030-01-10T00:00:00Z'), endAt: new Date('2030-01-11T00:00:00Z'), subtotal: 100, totalAmount: 100, currencyCode: 'INR', status: 'PAYMENT_PENDING', paymentStatus: 'pending', holdExpiresAt: new Date(Date.now() + 3600000) } }); const payment = await prisma.payment.create({ data: { bookingId: booking.id, userId: user.id, amount: 100, currencyCode: 'INR', provider: 'razorpay', providerOrderId: `order_${booking.id}`, status: 'pending' } }); return { user, car, booking, payment }; }
function event(orderId, changes = {}) { return { event: 'payment.captured', payload: { payment: { entity: { id: 'pay_1', order_id: orderId, amount: 10000, currency: 'INR', status: 'captured', ...changes } } } }; }
describe('Razorpay webhook processing', () => { let app; beforeAll(() => { app = createApp(); }); beforeEach(() => { resetStore(); jest.clearAllMocks(); razorpay.verifyWebhookSignature.mockImplementation((raw, signature) => Buffer.isBuffer(raw) && signature === 'good'); razorpay.parseWebhookEvent.mockImplementation((raw) => JSON.parse(raw.toString('utf8'))); }); const post = (payload, id = 'evt_1', signature = 'good') => request(app).post('/api/v1/payments/webhook/razorpay').set('Content-Type', 'application/json').set('X-Razorpay-Signature', signature).set('X-Razorpay-Event-Id', id).send(JSON.stringify(payload));
  it('requires the exact raw body, signature, and event ID before mutation', async () => { const f = await fixture(); expect((await post(event(f.payment.providerOrderId), 'evt_bad', 'bad')).status).toBe(400); expect((await post(event(f.payment.providerOrderId), '', 'good')).status).toBe(400); expect(await prisma.paymentWebhookEvent.count()).toBe(0); expect((await prisma.booking.findUnique({ where: { id: f.booking.id } })).status).toBe('PAYMENT_PENDING'); });
  it('captures, confirms atomically, stores a payload hash, and deduplicates', async () => { const f = await fixture(); const first = await post(event(f.payment.providerOrderId)); const second = await post(event(f.payment.providerOrderId)); expect(first.status).toBe(200); expect(second.status).toBe(200); expect((await prisma.payment.findUnique({ where: { id: f.payment.id } })).status).toBe('succeeded'); expect((await prisma.booking.findUnique({ where: { id: f.booking.id } })).status).toBe('CONFIRMED'); expect(await prisma.bookingStatusHistory.count()).toBe(1); const stored = await prisma.paymentWebhookEvent.findFirst(); expect(stored.payloadHash).toHaveLength(64); expect(await prisma.paymentWebhookEvent.count()).toBe(1); });
  it('marks amount/currency/payment-ID mismatch for review without confirming', async () => { const f = await fixture(); await post(event(f.payment.providerOrderId, { amount: 999 })); let saved = await prisma.payment.findUnique({ where: { id: f.payment.id } }); expect(saved).toMatchObject({ status: 'succeeded', operationalStatus: 'review_required' }); expect((await prisma.booking.findUnique({ where: { id: f.booking.id } })).status).toBe('PAYMENT_PENDING'); const g = await fixture(); await post(event(g.payment.providerOrderId, { currency: 'USD' }), 'evt_currency'); expect((await prisma.payment.findUnique({ where: { id: g.payment.id } })).operationalStatus).toBe('review_required'); });
  it('handles authorized and failed events without downgrading captured success', async () => { const f = await fixture(); await post({ ...event(f.payment.providerOrderId), event: 'payment.authorized' }, 'evt_authorized'); expect((await prisma.payment.findUnique({ where: { id: f.payment.id } })).status).toBe('processing'); await post(event(f.payment.providerOrderId), 'evt_capture'); await post({ ...event(f.payment.providerOrderId), event: 'payment.authorized' }, 'evt_late_authorized'); await post({ ...event(f.payment.providerOrderId, { error_description: 'nope' }), event: 'payment.failed' }, 'evt_late_failed'); expect((await prisma.payment.findUnique({ where: { id: f.payment.id } })).status).toBe('succeeded'); });
  it('records a matching failure without confirming its booking and ignores unknown orders', async () => { const f = await fixture(); await post({ ...event(f.payment.providerOrderId, { error_description: 'declined' }), event: 'payment.failed' }, 'evt_failed'); expect((await prisma.payment.findUnique({ where: { id: f.payment.id } })).status).toBe('failed'); expect((await prisma.booking.findUnique({ where: { id: f.booking.id } })).status).toBe('PAYMENT_PENDING'); expect((await post(event('order_unknown'), 'evt_unknown')).body.data.ignored).toBe(true); });
});
