'use strict';
jest.mock('../src/modules/payments/providers/razorpay', () => ({ createOrder: jest.fn(), verifyCheckoutSignature: jest.fn(), verifyWebhookSignature: jest.fn(), parseWebhookEvent: jest.fn() }));
const request = require('supertest'); const { createApp } = require('../src/app'); const { prisma, resetStore, seedUser } = require('./helpers/auth'); const { signAccessToken } = require('../src/utils/jwt'); const razorpay = require('../src/modules/payments/providers/razorpay'); const { minorUnits } = require('../src/modules/payments/service');
async function booking(userId, data = {}) { const car = await prisma.car.create({ data: { vendorId: 'v', branchId: 'b', registrationNumber: `PAY-${Math.random()}`, brand: 'T', model: 'P', manufacturingYear: 2025, status: 'available' } }); return prisma.booking.create({ data: { bookingNumber: `BK-${Math.random()}`, userId, vendorId: 'v', carId: car.id, startAt: new Date('2030-01-10T00:00:00Z'), endAt: new Date('2030-01-11T00:00:00Z'), subtotal: 1000, securityDeposit: 234.5, totalAmount: 1234.5, currencyCode: 'INR', status: 'PAYMENT_PENDING', paymentStatus: 'pending', holdExpiresAt: new Date(Date.now() + 600000), ...data } }); }
describe('Payment order API', () => { let app; let user; let token; beforeAll(() => { app = createApp(); }); beforeEach(async () => { resetStore(); jest.clearAllMocks(); user = await seedUser({ email: 'payment-order@example.test' }); token = signAccessToken({ sub: user.id }); razorpay.createOrder.mockResolvedValue({ id: 'order_test_1' }); });
  it('requires auth, strict input, and customer ownership', async () => { const own = await booking(user.id); const other = await seedUser({ email: 'other-payment@example.test' }); expect((await request(app).post('/api/v1/payments/orders').send({ bookingId: own.id })).status).toBe(401); expect((await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${signAccessToken({ sub: other.id })}`).send({ bookingId: own.id })).status).toBe(404); expect((await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: own.id, amount: 1 })).status).toBe(422); });
  it('uses only the persisted financial snapshot and safely reuses an order', async () => { const own = await booking(user.id); const first = await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: own.id }); const second = await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: own.id }); expect(first.status).toBe(201); expect(razorpay.createOrder).toHaveBeenCalledWith(expect.objectContaining({ amount: 123450, currency: 'INR' })); expect(first.body.data.payment).toMatchObject({ bookingId: own.id, providerOrderId: 'order_test_1', amount: 1234.5 }); expect(first.body.data).not.toHaveProperty('keySecret'); expect(second.status).toBe(201); expect(second.body.data.reused).toBe(true); expect(razorpay.createOrder).toHaveBeenCalledTimes(1); expect(await prisma.payment.count()).toBe(1); });
  it('rejects expired and already-paid bookings and records provider failure safely', async () => { const expired = await booking(user.id, { holdExpiresAt: new Date(Date.now() - 1) }); expect((await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: expired.id })).status).toBe(409); const paid = await booking(user.id, { paymentStatus: 'succeeded', status: 'CONFIRMED' }); expect((await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: paid.id })).status).toBe(409); const failing = await booking(user.id); razorpay.createOrder.mockRejectedValueOnce(new Error('gateway down')); expect((await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: failing.id })).status).toBe(503); expect((await prisma.payment.findFirst({ where: { bookingId: failing.id } })).status).toBe('failed'); });
  it('converts INR decimals without floating-point multiplication', () => { expect(minorUnits('299.00')).toBe(29900); expect(minorUnits('1234.5')).toBe(123450); expect(() => minorUnits('1.001')).toThrow(); });
  it('does not create a second remote order while a local attempt is in progress', async () => { const own = await booking(user.id); let release; razorpay.createOrder.mockImplementationOnce(() => new Promise((resolve) => { release = () => resolve({ id: 'order_race' }); })); const first = request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: own.id }).then((response) => response); for (let attempt = 0; !release && attempt < 20; attempt += 1) await new Promise((resolve) => setImmediate(resolve)); expect(release).toBeDefined(); const second = await request(app).post('/api/v1/payments/orders').set('Authorization', `Bearer ${token}`).send({ bookingId: own.id }); release(); expect((await first).status).toBe(201); expect(second.status).toBe(409); expect(razorpay.createOrder).toHaveBeenCalledTimes(1); });
});
