'use strict';
jest.mock('../src/modules/payments/providers/razorpay', () => ({ createOrder: jest.fn(), verifyCheckoutSignature: jest.fn(), verifyWebhookSignature: jest.fn(), parseWebhookEvent: jest.fn() }));
const { prisma, resetStore, seedUser } = require('./helpers/auth'); const razorpay = require('../src/modules/payments/providers/razorpay'); const { processWebhook } = require('../src/modules/payments/service');
async function createBooking(userId, carId, data = {}) { return prisma.booking.create({ data: { bookingNumber: `BK-${Math.random()}`, userId, vendorId: 'v', carId, startAt: new Date('2030-01-10T00:00:00Z'), endAt: new Date('2030-01-11T00:00:00Z'), subtotal: 100, totalAmount: 100, currencyCode: 'INR', status: 'PAYMENT_PENDING', paymentStatus: 'pending', holdExpiresAt: new Date(Date.now() - 1000), ...data } }); }
async function setup() { const user = await seedUser({ email: `late-${Math.random()}@example.test` }); const car = await prisma.car.create({ data: { vendorId: 'v', branchId: 'b', registrationNumber: `LATE-${Math.random()}`, brand: 'T', model: 'L', manufacturingYear: 2025, status: 'available' } }); const booking = await createBooking(user.id, car.id); const payment = await prisma.payment.create({ data: { bookingId: booking.id, userId: user.id, amount: 100, currencyCode: 'INR', provider: 'razorpay', providerOrderId: `order_${booking.id}`, status: 'pending' } }); return { user, car, booking, payment }; }
function captured(orderId, id = 'pay_late') { return Buffer.from(JSON.stringify({ event: 'payment.captured', payload: { payment: { entity: { id, order_id: orderId, amount: 10000, currency: 'INR', status: 'captured' } } } })); }
describe('Late captured payments', () => { beforeEach(() => { resetStore(); jest.clearAllMocks(); razorpay.parseWebhookEvent.mockImplementation((raw) => JSON.parse(raw.toString('utf8'))); });
  it('confirms an expired hold when its interval remains free', async () => { const f = await setup(); await processWebhook({ eventId: 'late_free', rawBody: captured(f.payment.providerOrderId) }); expect((await prisma.booking.findUnique({ where: { id: f.booking.id } })).status).toBe('CONFIRMED'); });
  it('keeps captured money successful but flags active/confirmed competing inventory', async () => { const f = await setup(); await createBooking(f.user.id, f.car.id, { bookingNumber: 'BK-COMPETING-HOLD', holdExpiresAt: new Date(Date.now() + 3600000) }); await processWebhook({ eventId: 'late_hold', rawBody: captured(f.payment.providerOrderId) }); const heldPayment = await prisma.payment.findUnique({ where: { id: f.payment.id } }); const heldBooking = await prisma.booking.findUnique({ where: { id: f.booking.id } }); expect(heldPayment).toMatchObject({ status: 'succeeded', operationalStatus: 'late_payment_conflict' }); expect(heldBooking.status).toBe('PAYMENT_PENDING'); const g = await setup(); await createBooking(g.user.id, g.car.id, { bookingNumber: 'BK-COMPETING-CONFIRMED', status: 'CONFIRMED', paymentStatus: 'succeeded' }); await processWebhook({ eventId: 'late_confirmed', rawBody: captured(g.payment.providerOrderId, 'pay_late_2') }); const confirmedPayment = await prisma.payment.findUnique({ where: { id: g.payment.id } }); expect(confirmedPayment.operationalStatus).toBe('late_payment_conflict'); });
});
