'use strict';
jest.mock('../src/modules/payments/providers/razorpay', () => ({ createRefund: jest.fn(), createOrder: jest.fn(), verifyCheckoutSignature: jest.fn(), verifyWebhookSignature: jest.fn(), parseWebhookEvent: jest.fn() }));
const { prisma, resetStore, seedUser } = require('./helpers/auth'); const { cancelBooking } = require('../src/modules/bookings/service'); const razorpay = require('../src/modules/payments/providers/razorpay');
const { reconcileProviderResult } = require('../src/modules/refunds/service');
async function fixture() { const user = await seedUser({ email: `refund-${Math.random()}@test` }); const booking = await prisma.booking.create({ data: { bookingNumber: `R-${Math.random()}`, userId: user.id, vendorId: 'v', carId: 'car', startAt: new Date(Date.now() + 86400000), endAt: new Date(Date.now() + 172800000), subtotal: 123.45, totalAmount: 123.45, currencyCode: 'INR', status: 'CONFIRMED', paymentStatus: 'succeeded' } }); const payment = await prisma.payment.create({ data: { bookingId: booking.id, userId: user.id, amount: 123.45, currencyCode: 'INR', provider: 'razorpay', providerPaymentId: `pay_${booking.id}`, status: 'succeeded' } }); return { user, booking, payment }; }
describe('durable refund orchestration', () => { beforeEach(() => { resetStore(); jest.clearAllMocks(); }); const run = (f, key = 'refund_key_123') => cancelBooking({ userId: f.user.id, bookingId: f.booking.id, idempotencyKey: key, reason: 'cancel' });
it('creates the durable intent before the provider call using persisted payment, amount, and key', async () => { const f = await fixture(); razorpay.createRefund.mockImplementation(async (args) => { const saved = await prisma.refund.findFirst({ where: { bookingId: f.booking.id } }); expect(saved).toBeTruthy(); expect(args).toMatchObject({ providerPaymentId: f.payment.providerPaymentId, amountMinor: 12345, idempotencyKey: saved.idempotencyKey }); return { providerRefundId: 'rfnd_pending', status: 'pending' }; }); await run(f); const refund = await prisma.refund.findFirst({ where: { bookingId: f.booking.id } }); expect(refund).toMatchObject({ status: 'pending', providerReference: 'rfnd_pending' }); expect((await prisma.payment.findUnique({ where: { id: f.payment.id } })).status).toBe('succeeded'); });
it('reconciles processed only to refunded financial states', async () => { const f = await fixture(); razorpay.createRefund.mockResolvedValue({ providerRefundId: 'rfnd_processed', status: 'processed' }); await run(f); expect((await prisma.refund.findFirst({ where: { bookingId: f.booking.id } })).status).toBe('succeeded'); expect((await prisma.payment.findUnique({ where: { id: f.payment.id } })).status).toBe('refunded'); expect((await prisma.booking.findUnique({ where: { id: f.booking.id } })).paymentStatus).toBe('refunded'); });
it('keeps payment succeeded for failed and ambiguous provider outcomes', async () => { const failed = await fixture(); razorpay.createRefund.mockResolvedValueOnce({ providerRefundId: 'rfnd_failed', status: 'failed' }); await run(failed); expect((await prisma.refund.findFirst({ where: { bookingId: failed.booking.id } })).status).toBe('failed'); expect((await prisma.payment.findUnique({ where: { id: failed.payment.id } })).status).toBe('succeeded'); const ambiguous = await fixture(); const error = new Error('timeout'); error.ambiguous = true; razorpay.createRefund.mockRejectedValueOnce(error); await expect(run(ambiguous)).rejects.toThrow('timeout'); expect((await prisma.refund.findFirst({ where: { bookingId: ambiguous.booking.id } })).status).toBe('pending'); expect((await prisma.payment.findUnique({ where: { id: ambiguous.payment.id } })).status).toBe('succeeded'); });
it('does not call the provider again or create another intent after processed success', async () => { const f = await fixture(); razorpay.createRefund.mockResolvedValue({ providerRefundId: 'rfnd_done', status: 'processed' }); await run(f); await run(f, 'different_request_key'); expect(await prisma.refund.count({ where: { bookingId: f.booking.id } })).toBe(1); expect(razorpay.createRefund).toHaveBeenCalledTimes(1); }); });
it('preserves durable retry identity after an ambiguous outcome', async () => { jest.clearAllMocks(); const f = await fixture(); const call = (key) => cancelBooking({ userId: f.user.id, bookingId: f.booking.id, idempotencyKey: key, reason: 'cancel' }); const error = new Error('timeout'); error.ambiguous = true; razorpay.createRefund.mockRejectedValueOnce(error).mockResolvedValueOnce({ providerRefundId: 'rfnd_retry', status: 'pending' }); await expect(call('refund_key_123')).rejects.toThrow('timeout'); const first = await prisma.refund.findFirst({ where: { bookingId: f.booking.id } }); await call('other_key'); const second = await prisma.refund.findFirst({ where: { bookingId: f.booking.id } }); expect(second.id).toBe(first.id); expect(second.idempotencyKey).toBe(first.idempotencyKey); expect(await prisma.refund.count({ where: { bookingId: f.booking.id } })).toBe(1); expect(razorpay.createRefund.mock.calls.map(([args]) => [args.providerPaymentId, args.amountMinor, args.idempotencyKey])).toEqual([[f.payment.providerPaymentId, 12345, first.idempotencyKey], [f.payment.providerPaymentId, 12345, first.idempotencyKey]]); });
it('marks a definitive provider rejection failed without changing the captured payment', async () => { jest.clearAllMocks(); const f = await fixture(); const error = new Error('rejected'); error.definitive = true; razorpay.createRefund.mockRejectedValueOnce(error); await expect(cancelBooking({userId:f.user.id,bookingId:f.booking.id,idempotencyKey:'reject',reason:'cancel'})).rejects.toThrow('rejected'); const refund=await prisma.refund.findFirst({where:{bookingId:f.booking.id}}); expect(refund.status).toBe('failed'); expect(refund.failedAt).toBeTruthy(); expect((await prisma.payment.findUnique({where:{id:f.payment.id}})).status).toBe('succeeded'); expect((await prisma.booking.findUnique({where:{id:f.booking.id}})).status).toBe('CANCELLED'); });
it('never overwrites an existing provider reference with a conflicting result', async () => { const f=await fixture(); const refund=await prisma.refund.create({data:{bookingId:f.booking.id,paymentId:f.payment.id,amount:123.45,currencyCode:'INR',provider:'razorpay',providerReference:'rfnd_existing_123',idempotencyKey:'existing_key',status:'pending'}}); await expect(reconcileProviderResult(refund,{providerRefundId:'rfnd_different_456',status:'processed'})).resolves.toBeNull(); expect((await prisma.refund.findUnique({where:{id:refund.id}})).providerReference).toBe('rfnd_existing_123'); expect((await prisma.payment.findUnique({where:{id:f.payment.id}})).status).toBe('succeeded'); });
