'use strict';

/**
 * Central registry of canonical error codes returned by the API.
 * Used in the standard error response's `error.code` field.
 */
module.exports = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Authentication / Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Not found
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // Conflict / database
  CONFLICT: 'CONFLICT',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  FOREIGN_KEY_VIOLATION: 'FOREIGN_KEY_VIOLATION',
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // Authentication / Authorization (Phase 20)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_ACCOUNT_BLOCKED: 'AUTH_ACCOUNT_BLOCKED',
  AUTH_ACCOUNT_DELETED: 'AUTH_ACCOUNT_DELETED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_REVOKED: 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_REFRESH_TOKEN_REUSE: 'AUTH_REFRESH_TOKEN_REUSE',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_PHONE_EXISTS: 'AUTH_PHONE_EXISTS',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_MAX_ATTEMPTS: 'AUTH_OTP_MAX_ATTEMPTS',
  AUTH_PASSWORD_INVALID: 'AUTH_PASSWORD_INVALID',
  AUTH_PASSWORD_WEAK: 'AUTH_PASSWORD_WEAK',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
AUTH_RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_VERIFICATION_TOKEN_INVALID: 'AUTH_VERIFICATION_TOKEN_INVALID',

  // Users (Phase 21)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_PHONE_EXISTS: 'USER_PHONE_EXISTS',
  USER_UPDATE_FAILED: 'USER_UPDATE_FAILED',
  USER_STATUS_INVALID: 'USER_STATUS_INVALID',
  USER_STATUS_TRANSITION_INVALID: 'USER_STATUS_TRANSITION_INVALID',
  USER_FORBIDDEN: 'USER_FORBIDDEN',
  USER_ALREADY_DELETED: 'USER_ALREADY_DELETED',
  USER_CANNOT_DELETE: 'USER_CANNOT_DELETE',
  USER_SELF_MODIFICATION_FORBIDDEN: 'USER_SELF_MODIFICATION_FORBIDDEN',
  USER_LAST_SUPER_ADMIN_PROTECTED: 'USER_LAST_SUPER_ADMIN_PROTECTED',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_FORBIDDEN: 'ADDRESS_FORBIDDEN',
  ADDRESS_ALREADY_DEFAULT: 'ADDRESS_ALREADY_DEFAULT',
  ADDRESS_INVALID: 'ADDRESS_INVALID',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PREFERENCE_UPDATE_FAILED: 'PREFERENCE_UPDATE_FAILED',
};
