'use strict';

const fs = require('fs');
const path = require('path');
const AppError = require('../../errors/AppError');
const httpStatus = require('../../constants/httpStatus');
const errorCodes = require('../../errors/errorCodes');
const { prisma } = require('../../config/database');
const { userKycDocumentDir } = require('../../middlewares/upload');
const { Prisma } = require('@prisma/client');

const missing = () => new AppError('KYC record not found.', httpStatus.NOT_FOUND, errorCodes.RESOURCE_NOT_FOUND);
const conflict = (message) => new AppError(message, httpStatus.CONFLICT, errorCodes.CONFLICT);
const reason = (value) => { if (!value || !String(value).trim()) throw new AppError('rejectionReason is required.', httpStatus.UNPROCESSABLE_ENTITY, errorCodes.VALIDATION_ERROR); return String(value).trim(); };
const audit = (db, reviewerId, action, entity, entityId, metadata) => db.auditLog.create({ data: { userId: reviewerId, action, module: 'kyc', entity, entityId, result: 'success', metadata: JSON.stringify(metadata) } });
const customerDocumentDto = (doc) => ({ id: doc.id, documentType: doc.documentType, status: doc.status, issuedAt: doc.issuedAt, expiresAt: doc.expiresAt, remarks: doc.remarks, rejectionReason: doc.rejectionReason, verifiedAt: doc.verifiedAt, createdAt: doc.createdAt, updatedAt: doc.updatedAt });
const vendorDocumentDto = (doc) => ({ id: doc.id, vendorId: doc.vendorId, documentType: doc.documentType, status: doc.status, issuedAt: doc.issuedAt, expiresAt: doc.expiresAt, remarks: doc.remarks, rejectionReason: doc.rejectionReason, verifiedAt: doc.verifiedAt, createdAt: doc.createdAt, updatedAt: doc.updatedAt });

async function customerProfile(db, userId) { const profile = await db.profile.findUnique({ where: { userId } }); if (!profile) throw missing(); return profile; }
async function vendor(db, vendorId) { const value = await db.vendor.findUnique({ where: { id: vendorId } }); if (!value) throw missing(); return value; }
async function noSelfVendorReview(db, reviewerId, vendorId) { if (await db.vendorMember.findFirst({ where: { vendorId, userId: reviewerId } })) throw conflict('Reviewers cannot review their own vendor.'); }
function pending(value) { if (value.status !== 'pending') throw conflict('KYC record is no longer pending.'); }
const lockStatements = {
  user_documents: (value) => Prisma.sql`SELECT id FROM user_documents WHERE id = ${value} FOR UPDATE`,
  profiles: (value) => Prisma.sql`SELECT id FROM profiles WHERE user_id = ${value} FOR UPDATE`,
  vendor_documents: (value) => Prisma.sql`SELECT id FROM vendor_documents WHERE id = ${value} FOR UPDATE`,
  vendors: (value) => Prisma.sql`SELECT id FROM vendors WHERE id = ${value} FOR UPDATE`,
};
async function lock(db, table, value) { if (db.$queryRaw) await db.$queryRaw(lockStatements[table](value)); }

const AdminKycService = {
  async listCustomers(status = 'pending') { const profiles = await prisma.profile.findMany({ where: { verificationStatus: status }, orderBy: { submittedAt: 'asc' } }); const data = []; for (const profile of profiles) { const user = await prisma.user.findUnique({ where: { id: profile.userId } }); if (user) data.push({ userId: user.id, name: user.name, email: user.email, verificationStatus: profile.verificationStatus, submittedAt: profile.submittedAt }); } return data; },
  async customerDetail(userId) { const [user, profile, documents] = await Promise.all([prisma.user.findUnique({ where: { id: userId } }), prisma.profile.findUnique({ where: { userId } }), prisma.userDocument.findMany({ where: { userId }, orderBy: { createdAt: 'desc' } })]); if (!user || !profile) throw missing(); return { user: { id: user.id, name: user.name, email: user.email }, profile: { verificationStatus: profile.verificationStatus, submittedAt: profile.submittedAt, verifiedAt: profile.verifiedAt, rejectionReason: profile.rejectionReason }, documents: documents.map(customerDocumentDto) }; },
  async reviewCustomerDocument(reviewerId, documentId, decision, rejectionReason) { return prisma.$transaction(async (db) => { await lock(db, 'user_documents', documentId); const doc = await db.userDocument.findUnique({ where: { id: documentId } }); if (!doc) throw missing(); if (doc.userId === reviewerId) throw conflict('Reviewers cannot review their own KYC.'); pending(doc); const data = decision === 'verify' ? { status: 'verified', verifiedAt: new Date(), verifiedBy: reviewerId, rejectionReason: null } : { status: 'rejected', verifiedAt: null, verifiedBy: reviewerId, rejectionReason: reason(rejectionReason) }; const updated = await db.userDocument.update({ where: { id: doc.id }, data }); await audit(db, reviewerId, `kyc.customer.document_${decision === 'verify' ? 'verified' : 'rejected'}`, 'user_document', doc.id, { oldStatus: 'pending', newStatus: data.status, documentType: doc.documentType }); return customerDocumentDto(updated); }); },
  async reviewCustomer(reviewerId, userId, decision, rejectionReason) { return prisma.$transaction(async (db) => { if (reviewerId === userId) throw conflict('Reviewers cannot review their own KYC.'); await lock(db, 'profiles', userId); const profile = await customerProfile(db, userId); pending({ status: profile.verificationStatus }); let data; if (decision === 'verify') { const licence = await db.userDocument.findFirst({ where: { userId, documentType: 'driving_license', status: 'verified' }, orderBy: { expiresAt: 'desc' } }); if (!licence || !licence.expiresAt || new Date(licence.expiresAt) <= new Date()) throw conflict('A current verified driving licence is required.'); data = { verificationStatus: 'verified', verifiedAt: new Date(), verifiedBy: reviewerId, rejectionReason: null }; } else data = { verificationStatus: 'rejected', verifiedAt: null, verifiedBy: reviewerId, rejectionReason: reason(rejectionReason) }; const updated = await db.profile.update({ where: { userId }, data }); await audit(db, reviewerId, `kyc.customer.${decision === 'verify' ? 'verified' : 'rejected'}`, 'profile', updated.id, { oldStatus: 'pending', newStatus: data.verificationStatus, userId }); return { verificationStatus: updated.verificationStatus, submittedAt: updated.submittedAt, verifiedAt: updated.verifiedAt, rejectionReason: updated.rejectionReason }; }); },
  async listVendors(status = 'pending') { return prisma.vendor.findMany({ where: { verificationStatus: status }, orderBy: { submittedAt: 'asc' } }); },
  async vendorDetail(vendorId) { const [value, documents] = await Promise.all([vendor(prisma, vendorId), prisma.vendorDocument.findMany({ where: { vendorId }, orderBy: { createdAt: 'desc' } })]); return { vendor: { id: value.id, companyName: value.companyName, legalName: value.legalName, verificationStatus: value.verificationStatus, submittedAt: value.submittedAt, verifiedAt: value.verifiedAt, rejectionReason: value.rejectionReason }, documents: documents.map(vendorDocumentDto) }; },
  async reviewVendorDocument(reviewerId, documentId, decision, rejectionReason) { return prisma.$transaction(async (db) => { await lock(db, 'vendor_documents', documentId); const doc = await db.vendorDocument.findUnique({ where: { id: documentId } }); if (!doc) throw missing(); await noSelfVendorReview(db, reviewerId, doc.vendorId); pending(doc); const data = decision === 'verify' ? { status: 'verified', verifiedAt: new Date(), verifiedBy: reviewerId, rejectionReason: null } : { status: 'rejected', verifiedAt: null, verifiedBy: reviewerId, rejectionReason: reason(rejectionReason) }; const updated = await db.vendorDocument.update({ where: { id: doc.id }, data }); await audit(db, reviewerId, `kyc.vendor.document_${decision === 'verify' ? 'verified' : 'rejected'}`, 'vendor_document', doc.id, { oldStatus: 'pending', newStatus: data.status, documentType: doc.documentType, vendorId: doc.vendorId }); return vendorDocumentDto(updated); }); },
  async reviewVendor(reviewerId, vendorId, decision, rejectionReason) { return prisma.$transaction(async (db) => { await lock(db, 'vendors', vendorId); await noSelfVendorReview(db, reviewerId, vendorId); const value = await vendor(db, vendorId); pending({ status: value.verificationStatus }); let data; if (decision === 'verify') { const evidence = await db.vendorDocument.findFirst({ where: { vendorId, status: 'verified' } }); if (!evidence) throw conflict('At least one verified vendor document is required.'); data = { verificationStatus: 'verified', verifiedAt: new Date(), verifiedBy: reviewerId, rejectionReason: null }; } else data = { verificationStatus: 'rejected', verifiedAt: null, verifiedBy: reviewerId, rejectionReason: reason(rejectionReason) }; const updated = await db.vendor.update({ where: { id: vendorId }, data }); await audit(db, reviewerId, `kyc.vendor.${decision === 'verify' ? 'verified' : 'rejected'}`, 'vendor', vendorId, { oldStatus: 'pending', newStatus: data.verificationStatus, vendorId }); return { id: updated.id, verificationStatus: updated.verificationStatus, verifiedAt: updated.verifiedAt, rejectionReason: updated.rejectionReason }; }); },
  async customerDownload(documentId) { const doc = await prisma.userDocument.findUnique({ where: { id: documentId } }); if (!doc) throw missing(); const file = path.resolve(userKycDocumentDir, path.basename(doc.storageKey || '')); if (!file.startsWith(`${userKycDocumentDir}${path.sep}`) || !fs.existsSync(file)) throw missing(); return { path: file, filename: path.basename(file) }; },
};
module.exports = { AdminKycService };
