'use strict';
const crypto = require('crypto');
const { Prisma } = require('@prisma/client');
const { prisma } = require('../../config/database');
const AppError = require('../../errors/AppError');
const httpStatus = require('../../constants/httpStatus');
const errorCodes = require('../../errors/errorCodes');
const razorpay = require('./providers/razorpay');
const invoices = require('../invoices/service');

const notFound = () => new AppError('Payment or booking not found.', httpStatus.NOT_FOUND, errorCodes.RESOURCE_NOT_FOUND);
const conflict = (message, code = errorCodes.CONFLICT) => new AppError(message, httpStatus.CONFLICT, code);
function minorUnits(value) { const match = String(value).match(/^(\d+)(?:\.(\d{1,2}))?$/); if (!match) throw new AppError('Payment amount cannot be represented in minor units.', httpStatus.UNPROCESSABLE_ENTITY, errorCodes.VALIDATION_ERROR); const paise = BigInt(match[1]) * 100n + BigInt((match[2] || '').padEnd(2, '0')); if (paise > BigInt(Number.MAX_SAFE_INTEGER)) throw new AppError('Payment amount is too large.', httpStatus.UNPROCESSABLE_ENTITY, errorCodes.VALIDATION_ERROR); return Number(paise); }
function dto(payment) { return { id: payment.id, bookingId: payment.bookingId, amount: payment.amount, currencyCode: payment.currencyCode, paymentMethod: payment.paymentMethod, provider: payment.provider, status: payment.status, operationalStatus: payment.operationalStatus, providerOrderId: payment.providerOrderId, providerPaymentId: payment.providerPaymentId, paidAt: payment.paidAt, failedAt: payment.failedAt, failureReason: payment.failureReason }; }
function payable(booking) { if (booking.status !== 'PAYMENT_PENDING' || booking.paymentStatus !== 'pending') throw conflict('Booking is not payable.', errorCodes.BOOKING_NOT_PAYABLE); if (!booking.holdExpiresAt || new Date(booking.holdExpiresAt) <= new Date()) throw conflict('Booking hold has expired.', errorCodes.BOOKING_HOLD_EXPIRED); }
async function activeAttempt(db, bookingId) { const payments = await db.payment.findMany({ where: { bookingId } }); return payments.find((payment) => payment.provider === 'razorpay' && ['pending', 'processing'].includes(payment.status)) || null; }
async function createOrder({ userId, bookingId }) { const claim = await prisma.$transaction(async (tx) => { const booking = await tx.booking.findFirst({ where: { id: bookingId, userId } }); if (!booking) throw notFound(); payable(booking); if (tx.$queryRaw) await tx.$queryRaw(Prisma.sql`SELECT id FROM bookings WHERE id = ${booking.id} FOR UPDATE`); const existing = await activeAttempt(tx, booking.id); if (existing) return { booking, payment: existing, reused: Boolean(existing.providerOrderId), inProgress: !existing.providerOrderId }; const payment = await tx.payment.create({ data: { bookingId: booking.id, userId, amount: booking.totalAmount, currencyCode: booking.currencyCode, paymentMethod: 'card', provider: 'razorpay', status: 'pending', operationalStatus: 'normal', transactionReference: `PAY-${crypto.randomUUID().replace(/-/g, '').slice(0, 24)}` } }); return { booking, payment, reused: false, inProgress: false }; });
  if (claim.inProgress) throw conflict('A payment order is already being created for this booking.', errorCodes.BOOKING_NOT_PAYABLE);
  if (claim.reused) return { payment: dto(claim.payment), keyId: require('../../config/env').env.RAZORPAY_KEY_ID, reused: true };
  if (claim.payment.providerOrderId) return { payment: dto(claim.payment), keyId: require('../../config/env').env.RAZORPAY_KEY_ID, reused: true };
  const another = await activeAttempt(prisma, bookingId); if (another && another.id !== claim.payment.id) throw conflict('A payment order is already being created for this booking.', errorCodes.BOOKING_NOT_PAYABLE);
  try { const order = await razorpay.createOrder({ amount: minorUnits(claim.booking.totalAmount), currency: claim.booking.currencyCode, receipt: claim.payment.transactionReference }); if (!order || !order.id) throw new Error('Razorpay did not return an order ID'); const payment = await prisma.payment.update({ where: { id: claim.payment.id }, data: { providerOrderId: order.id } }); return { payment: dto(payment), keyId: require('../../config/env').env.RAZORPAY_KEY_ID, reused: false }; } catch (err) { await prisma.payment.update({ where: { id: claim.payment.id }, data: { status: 'failed', failedAt: new Date(), failureReason: 'Payment provider order creation failed.' } }).catch(() => {}); if (err instanceof AppError) throw err; throw new AppError('Payment provider order creation failed.', httpStatus.SERVICE_UNAVAILABLE, errorCodes.PAYMENT_PROVIDER_UNAVAILABLE); }
}
async function verifyCheckout({ userId, bookingId, orderId, paymentId, signature }) { const payment = await prisma.payment.findFirst({ where: { bookingId, userId, provider: 'razorpay', providerOrderId: orderId } }); if (!payment) throw notFound(); if (payment.providerOrderId !== orderId) throw conflict('Payment order does not match.', errorCodes.PAYMENT_ORDER_MISMATCH); if (!razorpay.verifyCheckoutSignature({ orderId: payment.providerOrderId, paymentId, signature })) throw new AppError('Payment signature is invalid.', httpStatus.BAD_REQUEST, errorCodes.PAYMENT_SIGNATURE_INVALID); return { verified: true, payment: dto(payment) }; }
function blockingOther(bookings, current, now) { return bookings.some((booking) => booking.id !== current.id && new Date(booking.startAt) < new Date(current.endAt) && new Date(booking.endAt) > new Date(current.startAt) && ((['PENDING', 'PAYMENT_PENDING'].includes(booking.status) && booking.holdExpiresAt && new Date(booking.holdExpiresAt) > now) || ['CONFIRMED', 'ACTIVE'].includes(booking.status))); }
async function processWebhook({ eventId, rawBody }) { const event = razorpay.parseWebhookEvent(rawBody); const type = event.event; const entity = event.payload?.payment?.entity; const hash = crypto.createHash('sha256').update(rawBody).digest('hex'); try { return await prisma.$transaction(async (tx) => { const webhook = await tx.paymentWebhookEvent.create({ data: { provider: 'razorpay', providerEventId: eventId, eventType: String(type || 'unknown'), payloadHash: hash } }); if (!entity?.order_id) { await tx.paymentWebhookEvent.update({ where: { id: webhook.id }, data: { processedAt: new Date() } }); return { ignored: true }; } const payment = await tx.payment.findFirst({ where: { providerOrderId: entity.order_id } }); if (!payment) { await tx.paymentWebhookEvent.update({ where: { id: webhook.id }, data: { processedAt: new Date() } }); return { ignored: true }; } const link = (data) => tx.paymentWebhookEvent.update({ where: { id: webhook.id }, data: { paymentId: payment.id, processedAt: new Date(), ...data } }); if (type === 'payment.authorized') { if (payment.status !== 'succeeded') await tx.payment.update({ where: { id: payment.id }, data: { status: 'processing' } }); await link(); return { processed: true }; } if (type === 'payment.failed') { if (payment.status !== 'succeeded') await tx.payment.update({ where: { id: payment.id }, data: { status: 'failed', failedAt: new Date(), failureReason: String(entity.error_description || 'Razorpay payment failed.').slice(0, 500) } }); await link(); return { processed: true }; } if (type !== 'payment.captured') { await link(); return { ignored: true }; }
      const booking = await tx.booking.findUnique({ where: { id: payment.bookingId } }); if (!booking) { await link(); return { ignored: true }; } if (tx.$queryRaw) await tx.$queryRaw(Prisma.sql`SELECT id FROM cars WHERE id = ${booking.carId} FOR UPDATE`); const expected = minorUnits(payment.amount); const validAmount = Number(entity.amount) === expected; const validCurrency = String(entity.currency || '').toUpperCase() === payment.currencyCode.toUpperCase(); const existingProviderPayment = entity.id ? await tx.payment.findFirst({ where: { providerPaymentId: entity.id } }) : null; const samePayment = (!payment.providerPaymentId || payment.providerPaymentId === entity.id) && (!existingProviderPayment || existingProviderPayment.id === payment.id); if (!validAmount || !validCurrency || !samePayment) { await tx.payment.update({ where: { id: payment.id }, data: { status: 'succeeded', providerPaymentId: payment.providerPaymentId || null, paidAt: new Date(), operationalStatus: 'review_required' } }); await link(); return { reviewRequired: true }; }
      if (payment.status === 'succeeded' && booking.status === 'CONFIRMED') { await link(); return { processed: true, duplicatePayment: true }; } const now = new Date(); const bookings = await tx.booking.findMany({ where: { carId: booking.carId } }); if (blockingOther(bookings, booking, now)) { await tx.payment.update({ where: { id: payment.id }, data: { status: 'succeeded', providerPaymentId: entity.id, paidAt: new Date(), operationalStatus: 'late_payment_conflict' } }); await link(); return { latePaymentConflict: true }; }
      await tx.payment.update({ where: { id: payment.id }, data: { status: 'succeeded', providerPaymentId: entity.id, paidAt: new Date(), operationalStatus: 'normal' } }); await tx.booking.update({ where: { id: booking.id }, data: { status: 'CONFIRMED', paymentStatus: 'succeeded' } }); await tx.bookingStatusHistory.create({ data: { bookingId: booking.id, fromStatus: booking.status, toStatus: 'CONFIRMED', changedBy: null, reason: 'Razorpay payment captured.' } }); await link(); return { confirmed: true }; }); } catch (err) { if (err.code === 'P2002') return { duplicate: true }; throw err; } }
void processWebhook;
async function processWebhookLocked({ eventId, rawBody, afterPaymentUpdate }) {
  const event = razorpay.parseWebhookEvent(rawBody); const type = event.event; const entity = event.payload?.payment?.entity; const hash = crypto.createHash('sha256').update(rawBody).digest('hex');
  const candidate = entity?.order_id ? await prisma.payment.findFirst({ where: { providerOrderId: entity.order_id } }) : null; const candidateBooking = candidate ? await prisma.booking.findUnique({ where: { id: candidate.bookingId } }) : null;
  try { return await prisma.$transaction(async (tx) => {
    // IMPORTANT: this must remain the first transaction DB operation; MySQL read views must not predate the car lock.
    if (candidateBooking && tx.$queryRaw) await tx.$queryRaw(Prisma.sql`SELECT id FROM cars WHERE id = ${candidateBooking.carId} FOR UPDATE`);
    const webhook = await tx.paymentWebhookEvent.create({ data: { provider: 'razorpay', providerEventId: eventId, eventType: String(type || 'unknown'), payloadHash: hash } });
    const done = async (paymentId, result) => { await tx.paymentWebhookEvent.update({ where: { id: webhook.id }, data: { paymentId, processedAt: new Date() } }); return result; };
    if (!entity?.order_id) return done(null, { ignored: true });
    const payment = await tx.payment.findFirst({ where: { providerOrderId: entity.order_id } }); if (!payment) return done(null, { ignored: true });
    if (type === 'payment.authorized') { if (payment.status !== 'succeeded') await tx.payment.update({ where: { id: payment.id }, data: { status: 'processing' } }); return done(payment.id, { processed: true }); }
    if (type === 'payment.failed') { if (payment.status !== 'succeeded') await tx.payment.update({ where: { id: payment.id }, data: { status: 'failed', failedAt: new Date(), failureReason: String(entity.error_description || 'Razorpay payment failed.').slice(0, 500) } }); return done(payment.id, { processed: true }); }
    if (type !== 'payment.captured') return done(payment.id, { ignored: true });
    const booking = await tx.booking.findUnique({ where: { id: payment.bookingId } }); if (!booking || booking.carId !== candidateBooking?.carId) return done(payment.id, { ignored: true });
    const samePayment = !payment.providerPaymentId || payment.providerPaymentId === entity.id; const valid = Number(entity.amount) === minorUnits(payment.amount) && String(entity.currency || '').toUpperCase() === payment.currencyCode.toUpperCase() && samePayment;
    if (!valid) { await tx.payment.update({ where: { id: payment.id }, data: { status: 'succeeded', operationalStatus: 'review_required', paidAt: new Date() } }); return done(payment.id, { reviewRequired: true }); }
    if (booking.status === 'CANCELLED') { await tx.payment.update({ where: { id: payment.id }, data: { status: 'succeeded', providerPaymentId: entity.id, paidAt: new Date(), operationalStatus: 'late_payment_conflict' } }); return done(payment.id, { latePaymentConflict: true }); }
    if (payment.status === 'succeeded' && booking.status === 'CONFIRMED') return done(payment.id, { duplicatePayment: true });
    const all = await tx.booking.findMany({ where: { carId: booking.carId } }); if (blockingOther(all, booking, new Date())) { await tx.payment.update({ where: { id: payment.id }, data: { status: 'succeeded', providerPaymentId: entity.id, paidAt: new Date(), operationalStatus: 'late_payment_conflict' } }); return done(payment.id, { latePaymentConflict: true }); }
    const settledPayment = await tx.payment.update({ where: { id: payment.id }, data: { status: 'succeeded', providerPaymentId: entity.id, paidAt: new Date(), operationalStatus: 'normal' } }); if (afterPaymentUpdate) await afterPaymentUpdate(); const confirmedBooking = await tx.booking.update({ where: { id: booking.id }, data: { status: 'CONFIRMED', paymentStatus: 'succeeded' } }); await tx.bookingStatusHistory.create({ data: { bookingId: booking.id, fromStatus: booking.status, toStatus: 'CONFIRMED', changedBy: null, reason: 'Razorpay payment captured.' } }); await invoices.ensureForPaidBooking(tx, confirmedBooking, settledPayment); return done(payment.id, { confirmed: true });
  }); } catch (err) { if (err.code === 'P2002') return { duplicate: true }; throw err; }
}
async function getPayment(userId, paymentId) { const payment = await prisma.payment.findFirst({ where: { id: paymentId, userId } }); if (!payment) throw notFound(); return dto(payment); }
module.exports = { minorUnits, createOrder, verifyCheckout, processWebhook: processWebhookLocked, getPayment, dto };
