'use strict';
const { prisma }=require('../../config/database'); const {success,created}=require('../../utils/response'); const AppError=require('../../errors/AppError'); const httpStatus=require('../../constants/httpStatus'); const errorCodes=require('../../errors/errorCodes');
const publicInclude={images:true,features:true,pricings:{where:{status:'active'},orderBy:{createdAt:'desc'},take:1},branch:{include:{location:{include:{city:true}}}},vendor:{select:{id:true,companyName:true}}};
function publicDto(car){return {id:car.id,brand:car.brand,model:car.model,variant:car.variant,manufacturingYear:car.manufacturingYear,fuelType:car.fuelType,transmission:car.transmission,seatingCapacity:car.seatingCapacity,images:car.images||[],features:car.features||[],pricing:car.pricings?.[0]||null,branch:car.branch||null,vendor:car.vendor||null};}
async function get(id,include=publicInclude){const car=await prisma.car.findUnique({where:{id},include});if(!car||car.isDeleted)throw new AppError('Car not found.',httpStatus.NOT_FOUND,errorCodes.RESOURCE_NOT_FOUND);return car;}
async function list(req,res,next,publicOnly){try{const q=req.query,page=q.page||1,limit=q.limit||20;const where={isDeleted:false,...(publicOnly?{status:'available'}:{}),...(q.status?{status:q.status}:{}),...(q.vendorId?{vendorId:q.vendorId}:{}),...(q.branchId?{branchId:q.branchId}:{}),...(q.brand?{brand:{contains:q.brand}}:{}),...(q.fuelType?{fuelType:q.fuelType}:{}),...(q.transmission?{transmission:q.transmission}:{}),...(q.seatingCapacity?{seatingCapacity:{gte:q.seatingCapacity}}:{})};if(q.search)where.OR=[{brand:{contains:q.search}},{model:{contains:q.search}},{registrationNumber:{contains:q.search}}];const [data,total]=await Promise.all([prisma.car.findMany({where,skip:(page-1)*limit,take:limit,orderBy:{[q.sortBy||'createdAt']:q.sortOrder||'desc'},include:publicOnly?publicInclude:{branch:true,vendor:true}}),prisma.car.count({where})]);return success(res,{message:'Cars fetched successfully.',data:publicOnly?data.map(publicDto):data,meta:{page,limit,total,totalPages:Math.ceil(total/limit)}});}catch(e){return next(e);}}
async function validateRelations({ vendorId, branchId }) {
  const [vendor, branch] = await Promise.all([
    prisma.vendor.findUnique({ where: { id: vendorId } }),
    prisma.branch.findUnique({ where: { id: branchId } }),
  ]);
  if (!vendor || vendor.isDeleted || vendor.status !== 'active') {
    throw new AppError('Vendor not found.', httpStatus.NOT_FOUND, errorCodes.RESOURCE_NOT_FOUND);
  }
  if (!branch || branch.isDeleted || branch.status !== 'active') {
    throw new AppError('Branch not found.', httpStatus.NOT_FOUND, errorCodes.RESOURCE_NOT_FOUND);
  }
  if (branch.vendorId !== vendorId) {
    throw new AppError('Branch does not belong to vendor.', httpStatus.UNPROCESSABLE_ENTITY, errorCodes.UNPROCESSABLE_ENTITY);
  }
}
module.exports={featured:(req,res,next)=>list(req,res,next,true),search:(req,res,next)=>list(req,res,next,true),getPublic:async(req,res,next)=>{try{const car=await get(req.params.carId);if(car.status!=='available')throw new AppError('Car not found.',httpStatus.NOT_FOUND,errorCodes.RESOURCE_NOT_FOUND);return success(res,{message:'Car fetched successfully.',data:publicDto(car)});}catch(e){return next(e);}},listFleet:(req,res,next)=>list(req,res,next,false),create:async(req,res,next)=>{try{await validateRelations(req.body);return created(res,{message:'Car created successfully.',data:await prisma.car.create({data:req.body})});}catch(e){return next(e);}},getFleet:async(req,res,next)=>{try{return success(res,{message:'Car fetched successfully.',data:await get(req.params.carId,{branch:true,vendor:true,images:true,features:true,pricings:true,documents:true})});}catch(e){return next(e);}},update:async(req,res,next)=>{try{await get(req.params.carId);return success(res,{message:'Car updated successfully.',data:await prisma.car.update({where:{id:req.params.carId},data:req.body})});}catch(e){return next(e);}},updateStatus:async(req,res,next)=>{try{await get(req.params.carId);return success(res,{message:'Car status updated successfully.',data:await prisma.car.update({where:{id:req.params.carId},data:req.body})});}catch(e){return next(e);}},remove:async(req,res,next)=>{try{await get(req.params.carId);await prisma.car.update({where:{id:req.params.carId},data:{isDeleted:true,deletedAt:new Date(),status:'inactive'}});return success(res,{message:'Car deleted successfully.',data:{success:true}});}catch(e){return next(e);}}};

async function child(model, carId, id) { await get(carId); const value=await prisma[model].findUnique({where:{id}}); if(!value||value.carId!==carId) throw new AppError('Fleet record not found.',httpStatus.NOT_FOUND,errorCodes.RESOURCE_NOT_FOUND); return value; }
Object.assign(module.exports, {
  listDocuments:async(req,res,next)=>{try{await get(req.params.carId);return success(res,{message:'Car documents fetched successfully.',data:await prisma.carDocument.findMany({where:{carId:req.params.carId}})});}catch(e){return next(e);}},
  uploadDocument:async(req,res,next)=>{try{await get(req.params.carId);if(!req.file){const e=new Error('Document file is required.');e.statusCode=400;throw e;}const doc=await prisma.carDocument.create({data:{carId:req.params.carId,documentType:req.body.documentType,documentUrl:`/private/cars/${req.file.filename}`,issueDate:req.body.issueDate?new Date(req.body.issueDate):null,expiryDate:req.body.expiryDate?new Date(req.body.expiryDate):null,verificationStatus:req.body.verificationStatus||'pending'}});return created(res,{message:'Car document uploaded successfully.',data:doc});}catch(e){if(req.file){const fs=require('fs');const p=require('path').join(process.cwd(),'uploads','private','cars',req.file.filename);if(fs.existsSync(p))fs.unlinkSync(p);}return next(e);}},
  getDocument:async(req,res,next)=>{try{return success(res,{message:'Car document fetched successfully.',data:await child('carDocument',req.params.carId,req.params.documentId)});}catch(e){return next(e);}},
  updateDocument:async(req,res,next)=>{try{await child('carDocument',req.params.carId,req.params.documentId);return success(res,{message:'Car document updated successfully.',data:await prisma.carDocument.update({where:{id:req.params.documentId},data:req.body})});}catch(e){return next(e);}},
  downloadDocument:async(req,res,next)=>{try{const doc=await child('carDocument',req.params.carId,req.params.documentId);const fs=require('fs'),path=require('path');const root=path.resolve(process.cwd(),'uploads','private','cars');const file=path.resolve(root,path.basename(doc.documentUrl||''));if(!file.startsWith(`${root}${path.sep}`)||!fs.existsSync(file)){const e=new Error('Car document file not found.');e.statusCode=404;throw e;}return res.download(file,path.basename(file));}catch(e){return next(e);}},
  deleteDocument:async(req,res,next)=>{try{const doc=await child('carDocument',req.params.carId,req.params.documentId);await prisma.carDocument.delete({where:{id:doc.id}});const fs=require('fs'),path=require('path');const root=path.resolve(process.cwd(),'uploads','private','cars');const file=path.resolve(root,path.basename(doc.documentUrl||''));if(file.startsWith(`${root}${path.sep}`)&&fs.existsSync(file))fs.unlinkSync(file);return success(res,{message:'Car document deleted successfully.',data:{success:true}});}catch(e){return next(e);}},
  listImages:async(req,res,next)=>{try{await get(req.params.carId);return success(res,{message:'Car images fetched successfully.',data:await prisma.carImage.findMany({where:{carId:req.params.carId},orderBy:[{isPrimary:'desc'},{sortOrder:'asc'},{createdAt:'asc'}]})});}catch(e){return next(e);}},
  uploadImage:async(req,res,next)=>{try{await get(req.params.carId);if(!req.file){const e=new Error('Image file is required.');e.statusCode=400;throw e;}const count=await prisma.carImage.count({where:{carId:req.params.carId}});const image=await prisma.carImage.create({data:{carId:req.params.carId,imageUrl:`/uploads/cars/${req.file.filename}`,isPrimary:count===0,altText:req.body.altText||null}});return created(res,{message:'Car image uploaded successfully.',data:image});}catch(e){return next(e);}},
  primaryImage:async(req,res,next)=>{try{await child('carImage',req.params.carId,req.params.imageId);const image=await prisma.$transaction(async tx=>{await tx.carImage.updateMany({where:{carId:req.params.carId,isPrimary:true},data:{isPrimary:false}});return tx.carImage.update({where:{id:req.params.imageId},data:{isPrimary:true}});});return success(res,{message:'Primary image updated successfully.',data:image});}catch(e){return next(e);}},
  deleteImage:async(req,res,next)=>{try{const image=await child('carImage',req.params.carId,req.params.imageId);await prisma.carImage.delete({where:{id:image.id}});const fs=require('fs'),path=require('path');const dir=path.resolve(process.cwd(),'uploads','cars');const file=path.resolve(dir,path.basename(image.imageUrl||''));if(file.startsWith(`${dir}${path.sep}`)&&fs.existsSync(file))fs.unlinkSync(file);if(image.isPrimary){const replacement=await prisma.carImage.findFirst({where:{carId:req.params.carId},orderBy:{createdAt:'asc'}});if(replacement)await prisma.carImage.update({where:{id:replacement.id},data:{isPrimary:true}});}return success(res,{message:'Car image deleted successfully.',data:{success:true}});}catch(e){return next(e);}},
  listFeatures:async(req,res,next)=>{try{await get(req.params.carId);return success(res,{message:'Car features fetched successfully.',data:await prisma.carFeature.findMany({where:{carId:req.params.carId},orderBy:{name:'asc'}})});}catch(e){return next(e);}},
  createFeature:async(req,res,next)=>{try{await get(req.params.carId);return created(res,{message:'Car feature created successfully.',data:await prisma.carFeature.create({data:{carId:req.params.carId,...req.body}})});}catch(e){return next(e);}},
  updateFeature:async(req,res,next)=>{try{await child('carFeature',req.params.carId,req.params.featureId);return success(res,{message:'Car feature updated successfully.',data:await prisma.carFeature.update({where:{id:req.params.featureId},data:req.body})});}catch(e){return next(e);}},
  deleteFeature:async(req,res,next)=>{try{await child('carFeature',req.params.carId,req.params.featureId);await prisma.carFeature.delete({where:{id:req.params.featureId}});return success(res,{message:'Car feature deleted successfully.',data:{success:true}});}catch(e){return next(e);}},
});
