'use strict';

/**
 * In-memory Prisma mock for tests.
 * Activated only when TEST_DATABASE_MOCK=true (never in production).
 *
 * Provides functional in-memory model delegates for the auth-related models
 * (user, profile, role, permission, userRole, session, refreshToken, otp,
 * auditLog, activityLog) so tests can exercise the real auth service/controller
 * flows without touching a real database.
 *
 * This is a lightweight stand-in for the Prisma Client generated by
 * rentcar-database. It supports the specific query shapes used by the auth
 * module (findUnique/findFirst/findMany/create/update/updateMany with the
 * documented `where`/`include` shapes).
 */

const uuid = require('uuid');

function clone(value) {
  if (value === undefined) return undefined;
  return JSON.parse(JSON.stringify(value));
}

/** Deep simple equality for scalars (used by where matching). */
function valuesEqual(a, b) {
  const aNull = a === null || a === undefined;
  const bNull = b === null || b === undefined;
  // Treat null and undefined as equivalent so `where: { field: null }`
  // matches records where the field is unset (undefined).
  if (aNull || bNull) {
    return aNull && bNull;
  }
  return a === b;
}

/** Evaluate a Prisma-style `where` object against a record. */
function matchesWhere(record, where) {
  if (!where) return true;
  for (const [key, value] of Object.entries(where)) {
    if (value && typeof value === 'object' && !(value instanceof Date)) {
      if (value.in) {
        if (!value.in.includes(record[key])) return false;
        continue;
      }
      if (Object.prototype.hasOwnProperty.call(value, 'contains')) {
        if (!String(record[key] || '').includes(value.contains)) return false;
        continue;
      }
      if (Object.prototype.hasOwnProperty.call(value, 'equals')) {
        if (record[key] !== value.equals) return false;
        continue;
      }
      // Fallback: strict equality against the object value.
      if (record[key] !== value) return false;
      continue;
    }
    // Handle null equality (e.g. revokedAt: null).
    if (!valuesEqual(record[key], value)) return false;
  }
  return true;
}

/** Map a record, applying `include` relations where supported. */
function applyInclude(record, include, store, modelName) {
  if (!include || !record) return record;
  const out = { ...record };

  if (include.profile) {
    out.profile = store.profile.find((p) => p.userId === record.userId) || null;
  }

  if (include.role) {
    const roleRecord = store.role.find((r) => r.id === record.roleId);
    if (roleRecord) {
      // Descend into the nested include map (e.g. role: { include: { permissions } }).
      const nestedInclude =
        include.role && typeof include.role === 'object' && include.role.include
          ? include.role.include
          : undefined;
      out.role = applyInclude({ ...roleRecord }, nestedInclude, store, 'role');
    } else {
      out.role = null;
    }
  }

  // Permissions on a rolePermission row (relationship join).
  if (include.permissions && record.roleId) {
    out.permissions = store.rolePermission
      .filter((rp) => rp.roleId === record.roleId)
      .map((rp) => {
        let permission = store.permission.find((p) => p.id === rp.permissionId);
        if (permission && include.permissions.include && include.permissions.include.permission) {
          permission = { ...permission };
        }
        return { permission: permission || null };
      });
  }

  // Nested permissions directly on a role record (role.include.permissions).
  // A role stores its many-to-many permissions via rolePermission; the join
  // rows reference this role's id (record.id), not record.roleId.
  if (include.permissions && modelName === 'role' && record.id) {
    out.permissions = store.rolePermission
      .filter((rp) => rp.roleId === record.id)
      .map((rp) => {
        const permission = store.permission.find((p) => p.id === rp.permissionId);
        return { permission: permission || null };
      });
  }

  return out;
}

/**
 * Build a single model delegate with the Prisma-like methods the auth module
 * uses. `store` is the shared in-memory data store; `modelName` is the plural
 * array key.
 */
function createModel(modelName, store, hooks = {}) {
  const list = () => store[modelName];

  const api = {
    async findUnique({ where = {}, include } = {}) {
      const keys = Object.entries(where);
      const record = list().find((r) => keys.every(([k, v]) => valuesEqual(r[k], v)));
      if (!record) return null;
      return applyInclude({ ...record }, include, store, modelName);
    },

    async findFirst({ where = {}, orderBy = [], include } = {}) {
      let records = list().filter((r) => matchesWhere(r, where));
      if (orderBy) {
        const order = Array.isArray(orderBy) ? orderBy : [orderBy];
        for (const o of order.slice().reverse()) {
          const [field, dir] = Object.entries(o)[0];
          records = records.sort((a, b) => {
            const av = a[field];
            const bv = b[field];
            if (av === bv) return 0;
            if (av === undefined) return 1;
            if (bv === undefined) return -1;
            const cmp = av < bv ? -1 : av > bv ? 1 : 0;
            return dir === 'desc' ? -cmp : cmp;
          });
        }
      }
      const rec = records[0];
      if (!rec) return null;
      return applyInclude({ ...rec }, include, store, modelName);
    },

async findMany({ where = {}, orderBy = [], skip = 0, take = 0, include } = {}) {
      let records = list().filter((r) => matchesWhere(r, where));
      if (orderBy) {
        const order = Array.isArray(orderBy) ? orderBy : [orderBy];
        for (const o of order.slice().reverse()) {
          const [field, dir] = Object.entries(o)[0];
          records = records.sort((a, b) => {
            const av = a[field];
            const bv = b[field];
            if (av === bv) return 0;
            if (av === undefined) return 1;
            if (bv === undefined) return -1;
            const cmp = av < bv ? -1 : av > bv ? 1 : 0;
            return dir === 'desc' ? -cmp : cmp;
          });
        }
      }
      if (Number.isInteger(skip) && skip > 0) records = records.slice(skip);
      if (Number.isInteger(take) && take > 0) records = records.slice(0, take);
      return records.map((r) => applyInclude({ ...r }, include, store, modelName));
    },

    async count({ where = {} } = {}) {
      return list().filter((r) => matchesWhere(r, where)).length;
    },

    async create({ data }) {
      const id = data.id || uuid.v4();
      const now = new Date();
      const record = {
        ...clone(data),
        id,
        createdAt: data.createdAt ? new Date(data.createdAt) : now,
        updatedAt: data.updatedAt ? new Date(data.updatedAt) : now,
      };
      list().push(record);
      if (hooks.onCreate) hooks.onCreate(record, modelName);
      return { ...record };
    },

    async update({ where, data }) {
      const record = list().find((r) => r.id === where.id);
      if (!record) {
        const err = new Error('Record not found');
        err.code = 'P2025';
        throw err;
      }
      Object.assign(record, clone(data), { updatedAt: new Date() });
      return { ...record };
    },

    async updateMany({ where = {}, data }) {
      const targets = list().filter((r) => matchesWhere(r, where));
      targets.forEach((r) => Object.assign(r, clone(data), { updatedAt: new Date() }));
      return { count: targets.length };
    },

    async delete({ where }) {
      const idx = list().findIndex((r) => r.id === where.id);
      if (idx === -1) {
        const err = new Error('Record not found');
        err.code = 'P2025';
        throw err;
      }
      const [removed] = list().splice(idx, 1);
      return { ...removed };
    },
  };

  return api;
}

/**
 * Build the full in-memory Prisma mock.
 */
function createMockPrisma() {
  const store = {
    user: [],
    profile: [],
    address: [],
    role: [],
    permission: [],
    rolePermission: [],
    userRole: [],
    session: [],
    refreshToken: [],
    otp: [],
    auditLog: [],
    activityLog: [],
  };

  const prisma = {
    $connect: async () => {},
    $disconnect: async () => {},
    $queryRaw: async () => [{ 1n: 1n }],
    $queryRawUnsafe: async () => [{ 1n: 1n }],
    $transaction: async (fn) => {
      if (typeof fn !== 'function') return Promise.resolve(fn);

      // Snapshot the store so we can roll back on error.
      const snapshot = JSON.parse(JSON.stringify(store));
      try {
        return await fn(prisma);
      } catch (err) {
        // Restore the pre-transaction state.
        Object.keys(store).forEach((key) => {
          store[key].length = 0;
          store[key].push(...snapshot[key]);
        });
        throw err;
      }
    },
    $store: store,

user: createModel('user', store),
    profile: createModel('profile', store),
    address: createModel('address', store),
    role: createModel('role', store),
    permission: createModel('permission', store),
    rolePermission: createModel('rolePermission', store),
    userRole: createModel('userRole', store),
    session: createModel('session', store),
    refreshToken: createModel('refreshToken', store),
    otp: createModel('otp', store),
    auditLog: createModel('auditLog', store),
    activityLog: createModel('activityLog', store),
  };

  return prisma;
}

module.exports = { createMockPrisma };
